image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build
  - test 
  - deploy

build:
  stage: build
  script:
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://gcr.io < ${HOME}/gcloud-service-key.json
    - echo "building docker image"
    - docker build -t gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME .

test:
  stage: test
  script: 
    - echo "Running tests"

deploy_staging:
  before_script:
    - echo "pushing docker image"
    - docker push "gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME"
  image: google/cloud-sdk:latest
  stage: deploy
    script:
     - echo "deploying..."
  environment:
    name: staging
  when: manual
  only:
    - master
