image: docker:18.09.7

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:18.09.7-dind

stages:
  - build
  - mapping
  - test 
  - deploy-image
  - deploy-staging

build:
  stage: build
  image: microsoft/dotnet:latest
  before_script:
    - "dotnet restore"
  script:
    - "dotnet build"

mapping:
  stage: mapping
  image: python:latest
  script:
    - python3 env_mapper.py CONNECTION_STRING=$CONNECTION_STRING

test:
  stage: test
  image: microsoft/dotnet:latest
  script: 
    - echo "Running tests"

deploy-image:
  stage: deploy-image
  script:
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://gcr.io < ${HOME}/gcloud-service-key.json
    - echo "building and pushing docker image"
    - docker build -t gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME .
    - docker push "gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME"

deploy-staging:
  stage: deploy-staging
  image: google/cloud-sdk:latest
  script:
    - echo "deploying..."
  environment:
    name: staging
  when: manual
  only:
    - master