version: '3'

services: 
  dev-db:
    image: postgres:latest
    ports:
      - "8083:5432"
    volumes:
      - ./dev-database-creation-script.sql:/docker-entrypoint-initdb.d/dev-database-creation-script.sql
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  test-db:
    image: postgres:latest
    ports:
      - "8084:5432"
    volumes:
      - ./dev-database-creation-script.sql:/docker-entrypoint-initdb.d/dev-database-creation-script.sql
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"